from sqlalchemy.orm import Session
from database.model import create_bill_category, create_bill, get_single_provider_by_code, get_single_bill_category_by_code, check_bill_category_exist, check_if_bill_exists, get_single_service_by_code
import json

def seed_bill_categories(db: Session, commit: bool=False):
	data = [
		{
			'country_id': 1,
			'name': 'Airtime',
			'description': 'Nigerian Airtime Category',
			'code': 'ng_airtime',
			'status': 1,
		},
		{
			'country_id': 1,
			'name': 'Data',
			'description': 'Nigerian Data Category',
			'code': 'ng_data',
			'status': 1,
		},
		{
			'country_id': 1,
			'name': 'Internet',
			'description': 'Nigerian Internet Category',
			'code': 'ng_internet',
			'status': 0,
		},
		{
			'country_id': 1,
			'name': 'Utility Bills',
			'description': 'Nigerian Utility Bill Category',
			'code': 'ng_utility',
			'status': 0,
		},
		{
			'country_id': 1,
			'name': 'Cable',
			'description': 'Nigerian Cable Category',
			'code': 'ng_cable',
			'status': 0,
		},
		{
			'country_id': 1,
			'name': ' Betting',
			'description': 'Nigerian Betting Category',
			'code': 'ng_betting',
			'status': 0,
		},
		{
			'country_id': 1,
			'name': 'Nigerian Government',
			'description': 'Nigerian Government Category',
			'code': 'ng_govt',
			'status': 0,
		},
		{
			'country_id': 1,
			'name': 'Toll Services',
			'description': 'Nigerian Toll Category',
			'code': 'ng_toll',
			'status': 0,
		},
	]
	print(data)
	if len(data) > 0:
		for i in range(len(data)):
			if check_bill_category_exist(db=db, code=data[i]['code']) == False:
				create_bill_category(db=db, country_id=data[i]['country_id'], name=data[i]['name'], description=data[i]['description'], code=data[i]['code'], status=data[i]['status'], commit=commit)
	return True


def seed_bills(db: Session, commit: bool=False):
	data = [
		{
			'category': 'ng_airtime',
			'service': 'nigerian_airtime_service',
			'provider': 'squadco',
			'name': 'MTN Airtime',
			'description': 'MTN Airtime',
			'short_name': 'MTN',
			'label_name': 'Mobile Number',
			'code': 'bp_ng_mtn_airtime',
			'amount': 0,
			'minimum_amount': 50,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.02,
			'is_airtime': 1,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {},
		},
		{
			'category': 'ng_airtime',
			'service': 'nigerian_airtime_service',
			'provider': 'squadco',
			'name': 'Airtel Airtime',
			'description': 'Airtel Airtime',
			'short_name': 'Airtel',
			'label_name': 'Mobile Number',
			'code': 'bp_ng_airtel_airtime',
			'amount': 0,
			'minimum_amount': 50,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.02,
			'is_airtime': 1,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {},
		},
		{
			'category': 'ng_airtime',
			'service': 'nigerian_airtime_service',
			'provider': 'squadco',
			'name': 'Glo Airtime',
			'description': 'Glo Airtime',
			'short_name': 'Glo',
			'label_name': 'Mobile Number',
			'code': 'bp_ng_glo_airtime',
			'amount': 0,
			'minimum_amount': 50,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.02,
			'is_airtime': 1,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {},
		},
		{
			'category': 'ng_airtime',
			'service': 'nigerian_airtime_service',
			'provider': 'squadco',
			'name': '9mobile Airtime',
			'description': '9mobile Airtime',
			'short_name': '9mobile',
			'label_name': 'Mobile Number',
			'code': 'bp_ng_9mobile_airtime',
			'amount': 0,
			'minimum_amount': 50,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.02,
			'is_airtime': 1,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {},
		},
		{
			'category': 'ng_data',
			'service': 'nigerian_data_service',
			'provider': 'squadco',
			'name': 'MTN Data',
			'description': 'MTN Data',
			'short_name': 'MTN Data',
			'label_name': 'Mobile Number',
			'code': 'bp_ng_mtn_data',
			'amount': 0,
			'minimum_amount': 50,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.02,
			'is_airtime': 0,
			'is_data': 1,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'MTN',
				},
			},
		},
		{
			'category': 'ng_data',
			'service': 'nigerian_data_service',
			'provider': 'squadco',
			'name': 'Airtel Data',
			'description': 'Airtel Data',
			'short_name': 'Airtel Data',
			'label_name': 'Mobile Number',
			'code': 'bp_ng_airtel_data',
			'amount': 0,
			'minimum_amount': 50,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.02,
			'is_airtime': 0,
			'is_data': 1,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'Airtel',
				},
			},
		},
		{
			'category': 'ng_data',
			'service': 'nigerian_data_service',
			'provider': 'squadco',
			'name': 'Glo Data',
			'description': 'Glo Data',
			'short_name': 'Glo Data',
			'label_name': 'Mobile Number',
			'code': 'bp_ng_glo_data',
			'amount': 0,
			'minimum_amount': 50,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.02,
			'is_airtime': 0,
			'is_data': 1,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'GLO',
				},
			},
		},
		{
			'category': 'ng_data',
			'service': 'nigerian_data_service',
			'provider': 'squadco',
			'name': '9mobile Data',
			'description': '9mobile Data',
			'short_name': '9mobile Data',
			'label_name': 'Mobile Number',
			'code': 'bp_ng_9mobile_data',
			'amount': 0,
			'minimum_amount': 50,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.02,
			'is_airtime': 0,
			'is_data': 1,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': '9mobile',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Eko Electric (EKEDC) - Prepaid',
			'description': 'Eko Electric (EKEDC) - Prepaid',
			'short_name': 'EKEDC - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_eko_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'EKEDC',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Eko Electric (EKEDC) - Postpaid',
			'description': 'Eko Electric (EKEDC) - Postpaid',
			'short_name': 'EKEDC - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_eko_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'EKEDC',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Ikeja Electric (IE) - Prepaid',
			'description': 'Ikeja Electric (IE) - Prepaid',
			'short_name': 'IE - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_ikeja_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'IE',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Ikeja Electric (IE) - Postpaid',
			'description': 'Ikeja Electric (IE) - Postpaid',
			'short_name': 'IE - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_ikeja_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'IE',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Port Harcourt Electric (PHED) - Prepaid',
			'description': 'Port Harcourt Electric (PHED) - Prepaid',
			'short_name': 'PHED - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_phed_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'PHED',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Port Harcourt Electric (PHED) - Postpaid',
			'description': 'Port Harcourt Electric (PHED) - Postpaid',
			'short_name': 'PHED - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_phed_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'PHED',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Ibadan Disco (IBEDC) - Prepaid',
			'description': 'Ibadan Disco (IBEDC) - Prepaid',
			'short_name': 'IBEDC - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_ibedc_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'IBEDC',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Ibadan Disco (IBEDC) - Postpaid',
			'description': 'Ibadan Disco (IBEDC) - Postpaid',
			'short_name': 'IBEDC - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_ibedc_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'IBEDC',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Abuja Electric (AEDC) - Prepaid',
			'description': 'Abuja Electric (AEDC) - Prepaid',
			'short_name': 'AEDC - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_aedc_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'AEDC',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Abuja Electric (AEDC) - Postpaid',
			'description': 'Abuja Electric (AEDC) - Postpaid',
			'short_name': 'AEDC - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_aedc_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'AEDC',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Jos Electric (JED) - Prepaid',
			'description': 'Jos Electric (JED) - Prepaid',
			'short_name': 'JED - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_jed_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'JED',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Jos Electric (JED) - Postpaid',
			'description': 'Jos Electric (JED) - Postpaid',
			'short_name': 'JED - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_jed_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'JED',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Kaduna Electric (KEDCO) - Prepaid',
			'description': 'Kaduna Electric (KEDCO) - Prepaid',
			'short_name': 'KEDCO - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_kedco_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'KEDCO',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Kaduna Electric (KEDCO) - Postpaid',
			'description': 'Kaduna Electric (KEDCO) - Postpaid',
			'short_name': 'KEDCO - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_kedco_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'KEDCO',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Kano Electric (KAEDC) - Prepaid',
			'description': 'Kano Electric (KAEDC) - Prepaid',
			'short_name': 'KAEDC - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_kaedc_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'KAEDC',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Kano Electric (KAEDC) - Postpaid',
			'description': 'Kano Electric (KAEDC) - Postpaid',
			'short_name': 'KAEDC - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_kaedc_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'KAEDC',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Enugu Electric (EEDC) - Prepaid',
			'description': 'Enugu Electric (EEDC) - Prepaid',
			'short_name': 'EEDC - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_eedc_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'KAEDC',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Enugu Electric (EEDC) - Postpaid',
			'description': 'Enugu Electric (EEDC) - Postpaid',
			'short_name': 'EEDC - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_eedc_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'EEDC',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Aba Power (APLE) - Prepaid',
			'description': 'Aba Power (APLE) - Prepaid',
			'short_name': 'APLE - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_aple_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'APLE',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Aba Power (APLE) - Postpaid',
			'description': 'Aba Power (APLE) - Postpaid',
			'short_name': 'APLE - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_aple_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'APLE',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Yola Electric (YEDC) - Prepaid',
			'description': 'Yola Electric (YEDC) - Prepaid',
			'short_name': 'YEDC - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_yedc_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'YEDC',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Yola Electric (YEDC) - Postpaid',
			'description': 'Yola Electric (YEDC) - Postpaid',
			'short_name': 'YEDC - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_yedc_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'YEDC',
					'meter_type': 'postpaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Benin Electric (BEDC) - Prepaid',
			'description': 'Benin Electric (BEDC) - Prepaid',
			'short_name': 'BEDC - Prepaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_bedc_pre',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'BEDC',
					'meter_type': 'prepaid',
				},
			},
		},
		{
			'category': 'ng_utility',
			'service': 'nigerian_utility_bill_service',
			'provider': 'squadco',
			'name': 'Benin Electric (BEDC) - Postpaid',
			'description': 'Benin Electric (BEDC) - Postpaid',
			'short_name': 'BEDC - Postpaid',
			'label_name': 'Meter Number',
			'code': 'bp_ng_bedc_post',
			'amount': 0,
			'minimum_amount': 500,
			'maximum_amount': 10000000,
			'fee': 0,
			'commission': 0.9,
			'is_airtime': 0,
			'is_data': 0,
			'is_flat': 0,
			'meta_data': {
				'squadco': {
					'biller_name': 'BEDC',
					'meter_type': 'postpaid',
				},
			},
		},
	]
	print(data)
	if len(data) > 0:
		for i in range(len(data)):
			category_id = 0
			category = get_single_bill_category_by_code(db=db, code=data[i]['category'])
			if category is not None:
				category_id = category.id
			service_id = 0
			service = get_single_service_by_code(db=db, code=data[i]['service'])
			if service is not None:
				service_id = service.id
			provider_id = 0
			provider = get_single_provider_by_code(db=db, code=data[i]['provider'])
			if provider is not None:
				provider_id = provider.id
			create_bill(db=db, country_id=1, currency_id=1, category_id=category_id, service_id=service_id, provider_id=provider_id, name=data[i]['name'], description=data[i]['description'], short_name=data[i]['short_name'], label=data[i]['label_name'], code=data[i]['code'], amount=data[i]['amount'], minimum_amount=data[i]['minimum_amount'], maximum_amount=data[i]['maximum_amount'], fee=data[i]['fee'], commission=data[i]['commission'], is_airtime=data[i]['is_airtime'], is_data=data[i]['is_data'], is_flat=data[i]['is_flat'], meta_data=json.dumps(data[i]['meta_data']), status=1, commit=commit)
	True