from sqlalchemy.orm import Session
from database.model import get_single_provider_by_code, create_financial_institution

banks = [
    {"bank_name": "Sterling Bank", "nibbs_code": "000001", "cbn_code": "232"},
    {"bank_name": "Keystone Bank", "nibbs_code": "000002", "cbn_code": "082"},
    {"bank_name": "FCMB", "nibbs_code": "000003", "cbn_code": "214"},
    {"bank_name": "United Bank for Africa", "nibbs_code": "000004", "cbn_code": "033"},
    {"bank_name": "Diamond Bank", "nibbs_code": "000005", "cbn_code": "063"},
    {"bank_name": "JAIZ Bank", "nibbs_code": "000006", "cbn_code": "301"},
    {"bank_name": "Fidelity Bank", "nibbs_code": "000007", "cbn_code": "070"},
    {"bank_name": "Polaris Bank", "nibbs_code": "000008", "cbn_code": "076"},
    {"bank_name": "Citi Bank", "nibbs_code": "000009", "cbn_code": "023"},
    {"bank_name": "Ecobank Bank", "nibbs_code": "000010", "cbn_code": "050"},
    {"bank_name": "Unity Bank", "nibbs_code": "000011", "cbn_code": "215"},
    {"bank_name": "StanbicIBTC Bank", "nibbs_code": "000012", "cbn_code": "221"},
    {"bank_name": "GTBank Plc", "nibbs_code": "000013", "cbn_code": "058"},
    {"bank_name": "Access Bank", "nibbs_code": "000014", "cbn_code": "044"},
    {"bank_name": "Zenith Bank Plc", "nibbs_code": "000015", "cbn_code": "057"},
    {"bank_name": "First Bank of Nigeria", "nibbs_code": "000016", "cbn_code": "011"},
    {"bank_name": "Wema Bank", "nibbs_code": "000017", "cbn_code": "035"},
    {"bank_name": "Union Bank", "nibbs_code": "000018", "cbn_code": "032"},
    {"bank_name": "Enterprise Bank", "nibbs_code": "000019", "cbn_code": "084"},
    {"bank_name": "Heritage", "nibbs_code": "000020", "cbn_code": "030"},
    {"bank_name": "Standard Chartered", "nibbs_code": "000021", "cbn_code": "068"},
    {"bank_name": "Suntrust Bank", "nibbs_code": "000022", "cbn_code": "100"},
    {"bank_name": "Providus Bank", "nibbs_code": "000023", "cbn_code": "101"},
    {"bank_name": "Rand Merchant Bank", "nibbs_code": "000024", "cbn_code": ""},
    {"bank_name": "Titan Trust Bank", "nibbs_code": "000025", "cbn_code": "102"},
    {"bank_name": "Taj Bank", "nibbs_code": "000026", "cbn_code": "302"},
    {"bank_name": "Globus Bank", "nibbs_code": "000027", "cbn_code": "103"},
    {"bank_name": "Central Bank of Nigeria", "nibbs_code": "000028", "cbn_code": "001"},
    {"bank_name": "Lotus Bank", "nibbs_code": "000029", "cbn_code": "303"},
    {"bank_name": "Premium Trust Bank", "nibbs_code": "000031", "cbn_code": "105"},
    {"bank_name": "eNaira", "nibbs_code": "000033", "cbn_code": ""},
    {"bank_name": "Signature Bank", "nibbs_code": "000034", "cbn_code": "104"},
    {"bank_name": "Optimus Bank", "nibbs_code": "000036", "cbn_code": "107"},
    {"bank_name": "FEWCHORE FINANCE COMPANY LIMITED", "nibbs_code": "050002", "cbn_code": ""},
    {"bank_name": "SageGrey Finance Limited", "nibbs_code": "050003", "cbn_code": ""},
    {"bank_name": "AAA Finance", "nibbs_code": "050005", "cbn_code": ""},
    {"bank_name": "Branch International Financial Services", "nibbs_code": "050006", "cbn_code": ""},
    {"bank_name": "Tekla Finance Limited", "nibbs_code": "050007", "cbn_code": ""},
    {"bank_name": "Fast Credit", "nibbs_code": "050009", "cbn_code": ""},
    {"bank_name": "Fundquest Financial Services Limited", "nibbs_code": "050010", "cbn_code": ""},
    {"bank_name": "Enco Finance", "nibbs_code": "050012", "cbn_code": ""},
    {"bank_name": "Dignity Finance", "nibbs_code": "050013", "cbn_code": ""},
    {"bank_name": "Trinity Financial Services Limited", "nibbs_code": "050013", "cbn_code": ""},
    {"bank_name": "FSDH Merchant Bank", "nibbs_code": "400001", "cbn_code": "400"},
    {"bank_name": "Coronation Merchant Bank", "nibbs_code": "060001", "cbn_code": "559"},
    {"bank_name": "FBNQUEST Merchant Bank", "nibbs_code": "060002", "cbn_code": "560"},
    {"bank_name": "Nova Merchant Bank", "nibbs_code": "060003", "cbn_code": "561"},
    {"bank_name": "Greenwich Merchant Bank", "nibbs_code": "060004", "cbn_code": "562"},
    {"bank_name": "Omoluabi savings and loans", "nibbs_code": "070007", "cbn_code": ""},
    {"bank_name": "ASOSavings & Loans", "nibbs_code": "090001", "cbn_code": ""},
    {"bank_name": "Trustbond Mortgage Bank", "nibbs_code": "090005", "cbn_code": ""},
    {"bank_name": "SafeTrust", "nibbs_code": "090006", "cbn_code": ""},
    {"bank_name": "FBN Mortgages Limited", "nibbs_code": "090107", "cbn_code": ""},
    {"bank_name": "Imperial Homes Mortgage Bank", "nibbs_code": "100024", "cbn_code": ""},
    {"bank_name": "AG Mortgage Bank", "nibbs_code": "100028", "cbn_code": ""},
    {"bank_name": "Gateway Mortgage Bank", "nibbs_code": "070009", "cbn_code": ""},
    {"bank_name": "Abbey Mortgage Bank", "nibbs_code": "070010", "cbn_code": ""},
    {"bank_name": "Refuge Mortgage Bank", "nibbs_code": "070011", "cbn_code": ""},
    {"bank_name": "Lagos Building Investment Company", "nibbs_code": "070012", "cbn_code": ""},
    {"bank_name": "Platinum Mortgage Bank", "nibbs_code": "070013", "cbn_code": ""},
    {"bank_name": "First Generation Mortgage Bank", "nibbs_code": "070014", "cbn_code": ""},
    {"bank_name": "Brent Mortgage Bank", "nibbs_code": "070015", "cbn_code": ""},
    {"bank_name": "Infinity Trust Mortgage Bank", "nibbs_code": "070016", "cbn_code": ""},
    {"bank_name": "MayFresh Mortgage Bank", "nibbs_code": "070019", "cbn_code": ""},
    {"bank_name": "Jubilee-Life Mortgage Bank", "nibbs_code": "090003", "cbn_code": ""},
    {"bank_name": "Haggai Mortgage Bank Limited", "nibbs_code": "070017", "cbn_code": ""},
    {"bank_name": "Coop Mortgage Bank", "nibbs_code": "070021", "cbn_code": ""},
    {"bank_name": "Delta Trust Microfinance Bank", "nibbs_code": "070023", "cbn_code": ""},
    {"bank_name": "Homebase Mortgage Bank", "nibbs_code": "070024", "cbn_code": ""},
    {"bank_name": "Akwa Savings & Loans Limited", "nibbs_code": "070025", "cbn_code": ""},
    {"bank_name": "FHA Mortgage Bank", "nibbs_code": "070026", "cbn_code": ""},
    {"bank_name": "New Prudential Bank", "nibbs_code": "090108", "cbn_code": ""},
    {"bank_name": "NPF MicroFinance Bank", "nibbs_code": "070001", "cbn_code": ""},
    {"bank_name": "Fortis Microfinance Bank", "nibbs_code": "070002", "cbn_code": ""},
    {"bank_name": "Covenant MFB", "nibbs_code": "070006", "cbn_code": ""},
    {"bank_name": "Page Financials", "nibbs_code": "070008", "cbn_code": ""},
    {"bank_name": "Parralex Microfinance bank", "nibbs_code": "090004", "cbn_code": ""},
    {"bank_name": "Ekondo MFB", "nibbs_code": "090097", "cbn_code": ""},
    {"bank_name": "VFD MFB", "nibbs_code": "090110", "cbn_code": ""},
    {"bank_name": "FinaTrust Microfinance Bank", "nibbs_code": "090111", "cbn_code": ""},
    {"bank_name": "Seed Capital Microfinance Bank", "nibbs_code": "090112", "cbn_code": ""},
    {"bank_name": "Empire trust MFB", "nibbs_code": "090114", "cbn_code": ""},
    {"bank_name": "TCF MFB", "nibbs_code": "090115", "cbn_code": ""},
    {"bank_name": "AMML MFB", "nibbs_code": "090116", "cbn_code": ""},
    {"bank_name": "Boctrust Microfinance Bank", "nibbs_code": "090117", "cbn_code": ""},
    {"bank_name": "IBILE Microfinance Bank", "nibbs_code": "090118", "cbn_code": ""},
    {"bank_name": "Ohafia Microfinance Bank", "nibbs_code": "090119", "cbn_code": ""},
    {"bank_name": "Wetland Microfinance Bank", "nibbs_code": "090120", "cbn_code": ""},
    {"bank_name": "Hasal Microfinance Bank", "nibbs_code": "090121", "cbn_code": ""},
    {"bank_name": "Gowans Microfinance Bank", "nibbs_code": "090122", "cbn_code": ""},
    {"bank_name": "Verite Microfinance Bank", "nibbs_code": "090123", "cbn_code": ""},
    {"bank_name": "Xslnce Microfinance Bank", "nibbs_code": "090124", "cbn_code": ""},
    {"bank_name": "Regent Microfinance Bank", "nibbs_code": "090125", "cbn_code": ""},
    {"bank_name": "Fidfund Microfinance Bank", "nibbs_code": "090126", "cbn_code": ""},
    {"bank_name": "BC Kash Microfinance Bank", "nibbs_code": "090127", "cbn_code": ""},
    {"bank_name": "Ndiorah Microfinance Bank", "nibbs_code": "090128", "cbn_code": ""},
    {"bank_name": "Money Trust Microfinance Bank", "nibbs_code": "090129", "cbn_code": ""},
    {"bank_name": "Consumer Microfinance Bank", "nibbs_code": "090130", "cbn_code": ""},
    {"bank_name": "Allworkers Microfinance Bank", "nibbs_code": "090131", "cbn_code": ""},
    {"bank_name": "Richway Microfinance Bank", "nibbs_code": "090132", "cbn_code": ""},
    {"bank_name": "AL-Barakah Microfinance Bank", "nibbs_code": "090133", "cbn_code": ""},
    {"bank_name": "Accion Microfinance Bank", "nibbs_code": "090134", "cbn_code": ""},
    {"bank_name": "Personal Trust Microfinance Bank", "nibbs_code": "090135", "cbn_code": ""},
    {"bank_name": "Microcred Microfinance Bank", "nibbs_code": "090136", "cbn_code": ""},
    {"bank_name": "PecanTrust Microfinance Bank", "nibbs_code": "090137", "cbn_code": ""},
    {"bank_name": "Royal Exchange Microfinance Bank", "nibbs_code": "090138", "cbn_code": ""},
    {"bank_name": "Visa Microfinance Bank", "nibbs_code": "090139", "cbn_code": ""},
    {"bank_name": "Sagamu Microfinance Bank", "nibbs_code": "090140", "cbn_code": ""},
    {"bank_name": "Chikum Microfinance Bank", "nibbs_code": "090141", "cbn_code": ""},
    {"bank_name": "Yes Microfinance Bank", "nibbs_code": "090142", "cbn_code": ""},
    {"bank_name": "Apeks Microfinance Bank", "nibbs_code": "090143", "cbn_code": ""},
    {"bank_name": "CIT Microfinance Bank", "nibbs_code": "090144", "cbn_code": ""},
    {"bank_name": "Fullrange Microfinance Bank", "nibbs_code": "090145", "cbn_code": ""},
    {"bank_name": "Trident Microfinance Bank", "nibbs_code": "090146", "cbn_code": ""},
    {"bank_name": "Hackman Microfinance Bank", "nibbs_code": "090147", "cbn_code": ""},
    {"bank_name": "Bowen Microfinance Bank", "nibbs_code": "090148", "cbn_code": ""},
    {"bank_name": "IRL Microfinance Bank", "nibbs_code": "090149", "cbn_code": ""},
    {"bank_name": "Virtue Microfinance Bank", "nibbs_code": "090150", "cbn_code": ""},
    {"bank_name": "Mutual Trust Microfinance Bank", "nibbs_code": "090151", "cbn_code": ""},
    {"bank_name": "Nagarta Microfinance Bank", "nibbs_code": "090152", "cbn_code": ""},
    {"bank_name": "FFS Microfinance Bank", "nibbs_code": "090153", "cbn_code": ""},
    {"bank_name": "CEMCS Microfinance Bank", "nibbs_code": "090154", "cbn_code": ""},
    {"bank_name": "Advans La Fayette Microfinance Bank", "nibbs_code": "090155", "cbn_code": ""},
    {"bank_name": "e-Barcs Microfinance Bank", "nibbs_code": "090156", "cbn_code": ""},
    {"bank_name": "Infinity Microfinance Bank", "nibbs_code": "090157", "cbn_code": ""},
    {"bank_name": "Futo Microfinance Bank", "nibbs_code": "090158", "cbn_code": ""},
    {"bank_name": "Credit Afrique Microfinance Bank", "nibbs_code": "090159", "cbn_code": ""},
    {"bank_name": "Addosser Microfinance Bank", "nibbs_code": "090160", "cbn_code": ""},
    {"bank_name": "Okpoga Microfinance Bank", "nibbs_code": "090161", "cbn_code": ""},
    {"bank_name": "Stanford Microfinance Bank", "nibbs_code": "090162", "cbn_code": ""},
    {"bank_name": "First Royal Microfinance Bank", "nibbs_code": "090164", "cbn_code": ""},
    {"bank_name": "Petra Microfinance Bank", "nibbs_code": "090165", "cbn_code": ""},
    {"bank_name": "Eso-E Microfinance Bank", "nibbs_code": "090166", "cbn_code": ""},
    {"bank_name": "Daylight Microfinance Bank", "nibbs_code": "090167", "cbn_code": ""},
    {"bank_name": "Gashua Microfinance Bank", "nibbs_code": "090168", "cbn_code": ""},
    {"bank_name": "Alpha Kapital Microfinance Bank", "nibbs_code": "090169", "cbn_code": ""},
    {"bank_name": "Mainstreet Microfinance Bank", "nibbs_code": "090171", "cbn_code": ""},
    {"bank_name": "Astrapolaris Microfinance Bank", "nibbs_code": "090172", "cbn_code": ""},
    {"bank_name": "Reliance Microfinance Bank", "nibbs_code": "090173", "cbn_code": ""},
    {"bank_name": "Malachy Microfinance Bank", "nibbs_code": "090174", "cbn_code": ""},
    {"bank_name": "HighStreet Microfinance Bank", "nibbs_code": "090175", "cbn_code": ""},
    {"bank_name": "Bosak Microfinance Bank", "nibbs_code": "090176", "cbn_code": ""},
    {"bank_name": "Lapo Microfinance Bank", "nibbs_code": "090177", "cbn_code": ""},
    {"bank_name": "GreenBank Microfinance Bank", "nibbs_code": "090178", "cbn_code": ""},
    {"bank_name": "FAST Microfinance Bank", "nibbs_code": "090179", "cbn_code": ""},
    {"bank_name": "Amju Unique Microfinance Bank", "nibbs_code": "090180", "cbn_code": ""},
    {"bank_name": "Girei Microfinance Bank", "nibbs_code": "090186", "cbn_code": ""},
    {"bank_name": "Baines Credit Microfinance Bank", "nibbs_code": "090188", "cbn_code": ""},
    {"bank_name": "Esan Microfinance Bank", "nibbs_code": "090189", "cbn_code": ""},
    {"bank_name": "Mutual Benefits Microfinance Bank", "nibbs_code": "090190", "cbn_code": ""},
    {"bank_name": "KCMB Microfinance Bank", "nibbs_code": "090191", "cbn_code": ""},
    {"bank_name": "Midland Microfinance Bank", "nibbs_code": "090192", "cbn_code": ""},
    {"bank_name": "Unical Microfinance Bank", "nibbs_code": "090193", "cbn_code": ""},
    {"bank_name": "NIRSAL Microfinance Bank", "nibbs_code": "090194", "cbn_code": ""},
    {"bank_name": "Grooming Microfinance Bank", "nibbs_code": "090195", "cbn_code": ""},
    {"bank_name": "Pennywise Microfinance Bank", "nibbs_code": "090196", "cbn_code": ""},
    {"bank_name": "ABU Microfinance Bank", "nibbs_code": "090197", "cbn_code": ""},
    {"bank_name": "RenMoney Microfinance Bank", "nibbs_code": "090198", "cbn_code": ""},
    {"bank_name": "New Dawn Microfinance Bank", "nibbs_code": "090205", "cbn_code": ""},
    {"bank_name": "UNN MFB", "nibbs_code": "090251", "cbn_code": ""},
    {"bank_name": "Yobe Microfinance Bank", "nibbs_code": "090252", "cbn_code": ""},
    {"bank_name": "Coalcamp Microfinance Bank", "nibbs_code": "090254", "cbn_code": ""},
    {"bank_name": "Imo State Microfinance Bank", "nibbs_code": "090258", "cbn_code": ""},
    {"bank_name": "Alekun Microfinance Bank", "nibbs_code": "090259", "cbn_code": ""},
    {"bank_name": "Above Only Microfinance Bank", "nibbs_code": "090260", "cbn_code": ""},
    {"bank_name": "Quickfund Microfinance Bank", "nibbs_code": "090261", "cbn_code": ""},
    {"bank_name": "Stellas Microfinance Bank", "nibbs_code": "090262", "cbn_code": ""},
    {"bank_name": "Navy Microfinance Bank", "nibbs_code": "090263", "cbn_code": ""},
    {"bank_name": "Auchi Microfinance Bank", "nibbs_code": "090264", "cbn_code": ""},
    {"bank_name": "Lovonus Microfinance Bank", "nibbs_code": "090265", "cbn_code": ""},
    {"bank_name": "Uniben Microfinance Bank", "nibbs_code": "090266", "cbn_code": ""},
    {"bank_name": "Kuda Microfinance Bank", "nibbs_code": "090267", "cbn_code": ""},
    {"bank_name": "Adeyemi College Staff Microfinance Bank", "nibbs_code": "090268", "cbn_code": ""},
    {"bank_name": "Greenville Microfinance Bank", "nibbs_code": "090269", "cbn_code": ""},
    {"bank_name": "AB Microfinance Bank", "nibbs_code": "090270", "cbn_code": ""},
    {"bank_name": "Lavender Microfinance Bank", "nibbs_code": "090271", "cbn_code": ""},
    {"bank_name": "Olabisi Onabanjo University Microfinance Bank", "nibbs_code": "090272", "cbn_code": ""},
    {"bank_name": "Emeralds Microfinance Bank", "nibbs_code": "090273", "cbn_code": ""},
    {"bank_name": "Prestige Microfinance Bank", "nibbs_code": "090274", "cbn_code": ""},
    {"bank_name": "Trustfund Microfinance Bank", "nibbs_code": "090276", "cbn_code": ""},
    {"bank_name": "Al-Hayat Microfinance Bank", "nibbs_code": "090277", "cbn_code": ""},
    {"bank_name": "Glory Microfinance Bank", "nibbs_code": "090278", "cbn_code": ""},
    {"bank_name": "Ikire Microfinance Bank", "nibbs_code": "090279", "cbn_code": ""},
    {"bank_name": "Megapraise Microfinance Bank", "nibbs_code": "090280", "cbn_code": ""},
    {"bank_name": "MintFinex Microfinance Bank", "nibbs_code": "090281", "cbn_code": ""},
    {"bank_name": "Arise Microfinance Bank", "nibbs_code": "090282", "cbn_code": ""},
    {"bank_name": "Nnew Women Microfinance Bank", "nibbs_code": "090283", "cbn_code": ""},
    {"bank_name": "First Option Microfinance Bank", "nibbs_code": "090285", "cbn_code": ""},
    {"bank_name": "Safe Haven Microfinance Bank", "nibbs_code": "090286", "cbn_code": ""},
    {"bank_name": "AssetMatrix Microfinance Bank", "nibbs_code": "090287", "cbn_code": ""},
    {"bank_name": "Pillar Microfinance Bank", "nibbs_code": "090289", "cbn_code": ""},
    {"bank_name": "FCT Microfinance Bank", "nibbs_code": "090290", "cbn_code": ""},
    {"bank_name": "Halal Credit Microfinance Bank", "nibbs_code": "090291", "cbn_code": ""},
    {"bank_name": "Afekhafe Microfinance Bank", "nibbs_code": "090292", "cbn_code": ""},
    {"bank_name": "Brethren Microfinance Bank", "nibbs_code": "090293", "cbn_code": ""},
    {"bank_name": "Eagle Flight Microfinance Bank", "nibbs_code": "090294", "cbn_code": ""},
    {"bank_name": "Omiye Microfinance Bank", "nibbs_code": "090295", "cbn_code": ""},
    {"bank_name": "Polyunwana Microfinance Bank", "nibbs_code": "090296", "cbn_code": ""},
    {"bank_name": "Alert Microfinance Bank", "nibbs_code": "090297", "cbn_code": ""},
    {"bank_name": "FedPoly Nasarawa Microfinance Bank", "nibbs_code": "090298", "cbn_code": ""},
    {"bank_name": "Kontagora Microfinance Bank", "nibbs_code": "090299", "cbn_code": ""},
    {"bank_name": "Purplemoney Microfinance Bank", "nibbs_code": "090303", "cbn_code": ""},
    {"bank_name": "Evangel Microfinance Bank", "nibbs_code": "090304", "cbn_code": ""},
    {"bank_name": "Sulspap Microfinance Bank", "nibbs_code": "090305", "cbn_code": ""},
    {"bank_name": "Aramoko Microfinance Bank", "nibbs_code": "090307", "cbn_code": ""},
    {"bank_name": "Brightway Microfinance Bank", "nibbs_code": "090308", "cbn_code": ""},
    {"bank_name": "EdFin Microfinance Bank", "nibbs_code": "090310", "cbn_code": ""},
    {"bank_name": "U & C Microfinance Bank", "nibbs_code": "090315", "cbn_code": ""},
    {"bank_name": "PatrickGold Microfinance Bank", "nibbs_code": "090317", "cbn_code": ""},
    {"bank_name": "Federal University Dutse Microfinance Bank", "nibbs_code": "090318", "cbn_code": ""},
    {"bank_name": "KadPoly Microfinance Bank", "nibbs_code": "090320", "cbn_code": ""},
    {"bank_name": "MayFair Microfinance Bank", "nibbs_code": "090321", "cbn_code": ""},
    {"bank_name": "Rephidim Microfinance Bank", "nibbs_code": "090322", "cbn_code": ""},
    {"bank_name": "Mainland Microfinance Bank", "nibbs_code": "090323", "cbn_code": ""},
    {"bank_name": "Ikenne Microfinance Bank", "nibbs_code": "090324", "cbn_code": ""},
    {"bank_name": "Sparkle", "nibbs_code": "090325", "cbn_code": ""},
    {"bank_name": "Balogun Gambari Microfinance Bank", "nibbs_code": "090326", "cbn_code": ""},
    {"bank_name": "Trust Microfinance Bank", "nibbs_code": "090327", "cbn_code": ""},
    {"bank_name": "Eyowo", "nibbs_code": "090328", "cbn_code": ""},
    {"bank_name": "Neptune Microfinance Bank", "nibbs_code": "090329", "cbn_code": ""},
    {"bank_name": "UNAAB Microfinance Bank", "nibbs_code": "090331", "cbn_code": ""},
    {"bank_name": "Evergreen Microfinance Bank", "nibbs_code": "090332", "cbn_code": ""},
    {"bank_name": "Oche Microfinance Bank", "nibbs_code": "090333", "cbn_code": ""},
    {"bank_name": "Iyeru Okin Microfinance Bank", "nibbs_code": "090337", "cbn_code": ""},
    {"bank_name": "Jessefield Microfinance Bank", "nibbs_code": "090352", "cbn_code": ""},
    {"bank_name": "BIPC Microfinance Bank", "nibbs_code": "090336", "cbn_code": ""},
    {"bank_name": "OAU Microfinance Bank", "nibbs_code": "090345", "cbn_code": ""},
    {"bank_name": "Nassarawa Microfinance Bank", "nibbs_code": "090349", "cbn_code": ""},
    {"bank_name": "CashConnect Microfinance Bank", "nibbs_code": "090360", "cbn_code": ""},
    {"bank_name": "Molusi Microfinance Bank", "nibbs_code": "090362", "cbn_code": ""},
    {"bank_name": "Headway Microfinance Bank", "nibbs_code": "090363", "cbn_code": ""},
    {"bank_name": "Nuture Microfinance Bank", "nibbs_code": "090364", "cbn_code": ""},
    {"bank_name": "Corestep Microfinance Bank", "nibbs_code": "090365", "cbn_code": ""},
    {"bank_name": "Firmus Microfinance Bank", "nibbs_code": "090366", "cbn_code": ""},
    {"bank_name": "Seedvest Microfinance Bank", "nibbs_code": "090369", "cbn_code": ""},
    {"bank_name": "Ilisan Microfinance Bank", "nibbs_code": "090370", "cbn_code": ""},
    {"bank_name": "Legend Microfinance Bank", "nibbs_code": "090372", "cbn_code": ""},
    {"bank_name": "Think Finance Microfinance Bank", "nibbs_code": "090373", "cbn_code": ""},
    {"bank_name": "Coastline Microfinance Bank", "nibbs_code": "090374", "cbn_code": ""},
    {"bank_name": "Apple Microfinance Bank", "nibbs_code": "090376", "cbn_code": ""},
    {"bank_name": "Isaleoyo Microfinance Bank", "nibbs_code": "090377", "cbn_code": ""},
    {"bank_name": "New Golden Pastures Microfinance Bank", "nibbs_code": "090378", "cbn_code": ""},
    {"bank_name": "GTI Microfinance Bank", "nibbs_code": "090385", "cbn_code": ""},
    {"bank_name": "Interland Microfinance Bank", "nibbs_code": "090386", "cbn_code": ""},
    {"bank_name": "EK-Reliable Microfinance Bank", "nibbs_code": "090389", "cbn_code": ""},
    {"bank_name": "Davodani Microfinance Bank", "nibbs_code": "090391", "cbn_code": ""},
    {"bank_name": "Conpro Microfinance Bank", "nibbs_code": "090380", "cbn_code": ""},
    {"bank_name": "Bridgeway Microfinance Bank", "nibbs_code": "090393", "cbn_code": ""},
    {"bank_name": "Amac Microfinance Bank", "nibbs_code": "090394", "cbn_code": ""},
    {"bank_name": "Borgu Microfinance Bank", "nibbs_code": "090395", "cbn_code": ""},
    {"bank_name": "Oscotech Microfinance Bank", "nibbs_code": "090396", "cbn_code": ""},
    {"bank_name": "Nwannegadi Microfinance Bank", "nibbs_code": "090399", "cbn_code": ""},
    {"bank_name": "Federal Polytechnic Nekede Microfinance Bank", "nibbs_code": "090398", "cbn_code": ""},
    {"bank_name": "Shepherd Trust Microfinance Bank", "nibbs_code": "090401", "cbn_code": ""},
    {"bank_name": "UDA Microfinance Bank", "nibbs_code": "090403", "cbn_code": ""},
    {"bank_name": "Olowolagba Microfinance Bank", "nibbs_code": "090404", "cbn_code": ""},
    {"bank_name": "Rolez Microfinance Bank", "nibbs_code": "090405", "cbn_code": ""},
    {"bank_name": "Business Support Microfinance Bank", "nibbs_code": "090406", "cbn_code": ""},
    {"bank_name": "FCMB BETA", "nibbs_code": "090409", "cbn_code": ""},
    {"bank_name": "GMB Microfinance Bank", "nibbs_code": "090408", "cbn_code": ""},
    {"bank_name": "Maritime Microfinance Bank", "nibbs_code": "090410", "cbn_code": ""},
    {"bank_name": "Giginya Microfinance bank", "nibbs_code": "090411", "cbn_code": ""},
    {"bank_name": "Preeminent Microfinance Bank", "nibbs_code": "090412", "cbn_code": ""},
    {"bank_name": "BOI Microfinance Bank", "nibbs_code": "090444", "cbn_code": ""},
    {"bank_name": "Moyofade Microfinance Bank", "nibbs_code": "090448", "cbn_code": ""},
    {"bank_name": "Mkobo Microfinance Bank", "nibbs_code": "090455", "cbn_code": ""},
    {"bank_name": "Rehoboth Microfinance Bank", "nibbs_code": "090463", "cbn_code": ""},
    {"bank_name": "Unimaid Microfinance Bank", "nibbs_code": "090464", "cbn_code": ""},
    {"bank_name": "OLOFIN OWENA Microfinance Bank", "nibbs_code": "090468", "cbn_code": ""},
    {"bank_name": "Assets Microfinance Bank", "nibbs_code": "090473", "cbn_code": ""},
    {"bank_name": "UniUyo Microfinance Bank", "nibbs_code": "090338", "cbn_code": ""},
    {"bank_name": "YCT Microfinance Bank", "nibbs_code": "090466", "cbn_code": ""},
    {"bank_name": "Good Neigbours Microfinance Bank", "nibbs_code": "090467", "cbn_code": ""},
    {"bank_name": "Oluchukwu Microfinance Bank", "nibbs_code": "090471", "cbn_code": ""},
    {"bank_name": "Maintrust Microfinance Bank", "nibbs_code": "090465", "cbn_code": ""},
    {"bank_name": "Aniocha Microfinance bank", "nibbs_code": "090469", "cbn_code": ""},
    {"bank_name": "Caretaker Microfinance Bank", "nibbs_code": "090472", "cbn_code": ""},
    {"bank_name": "Giant Stride Microfinance Bank", "nibbs_code": "090475", "cbn_code": ""},
    {"bank_name": "Balogun Fulani Microfinance Bank", "nibbs_code": "090181", "cbn_code": ""},
    {"bank_name": "Verdant Microfinance Bank", "nibbs_code": "090474", "cbn_code": ""},
    {"bank_name": "Changan RTS Microfinance Bank", "nibbs_code": "090470", "cbn_code": ""},
    {"bank_name": "Anchorage Microfinance Bank", "nibbs_code": "090476", "cbn_code": ""},
    {"bank_name": "Light MFB", "nibbs_code": "090477", "cbn_code": ""},
    {"bank_name": "Cintrust Microfinance Bank", "nibbs_code": "090480", "cbn_code": ""},
    {"bank_name": "Fedeth Microfinance Bank", "nibbs_code": "090482", "cbn_code": ""},
    {"bank_name": "Ada Microfinance Bank", "nibbs_code": "090483", "cbn_code": ""},
    {"bank_name": "Ibu-Aje Microfinance Bank", "nibbs_code": "090488", "cbn_code": ""},
    {"bank_name": "Alvana Microfinance Bank", "nibbs_code": "090489", "cbn_code": ""},
    {"bank_name": "Chukwunenye MFB", "nibbs_code": "090490", "cbn_code": ""},
    {"bank_name": "Nsuk MFB", "nibbs_code": "090491", "cbn_code": ""},
    {"bank_name": "Oraukwu MFB", "nibbs_code": "090492", "cbn_code": ""},
    {"bank_name": "Boji MFB", "nibbs_code": "090494", "cbn_code": ""},
    {"bank_name": "Goodnews Microfinance Bank", "nibbs_code": "090495", "cbn_code": ""},
    {"bank_name": "Randalpha Microfinance Bank", "nibbs_code": "090496", "cbn_code": ""},
    {"bank_name": "Pristine Divitis Microfinance Bank", "nibbs_code": "090499", "cbn_code": ""},
    {"bank_name": "Shalom Microfinance Bank", "nibbs_code": "090502", "cbn_code": ""},
    {"bank_name": "Projects Microfinance Bank", "nibbs_code": "090503", "cbn_code": ""},
    {"bank_name": "Zikora Microfinance Bank", "nibbs_code": "090504", "cbn_code": ""},
    {"bank_name": "Nigerian Prisons Microfinance Bank", "nibbs_code": "090505", "cbn_code": ""},
    {"bank_name": "Solid Allianze MFB", "nibbs_code": "090506", "cbn_code": ""},
    {"bank_name": "FIMS MFB", "nibbs_code": "090507", "cbn_code": ""},
    {"bank_name": "SEAP Microfinance Bank", "nibbs_code": "090513", "cbn_code": ""},
    {"bank_name": "RIMA Growth Pathway Microfinance Bank", "nibbs_code": "090515", "cbn_code": ""},
    {"bank_name": "Numo Microfinance Bank", "nibbs_code": "090516", "cbn_code": ""},
    {"bank_name": "Uhuru Microfinance Bank", "nibbs_code": "090517", "cbn_code": ""},
    {"bank_name": "Afemai Microfinance Bank", "nibbs_code": "090518", "cbn_code": ""},
    {"bank_name": "Iboma Fadama Microfinance Bank", "nibbs_code": "090519", "cbn_code": ""},
    {"bank_name": "Chase Microfinance Bank", "nibbs_code": "090523", "cbn_code": ""},
    {"bank_name": "Solidrock microfinance Bank", "nibbs_code": "090524", "cbn_code": ""},
    {"bank_name": "TripleA Microfinance Bank", "nibbs_code": "090525", "cbn_code": ""},
    {"bank_name": "Crescent Microfinance Bank", "nibbs_code": "090526", "cbn_code": ""},
    {"bank_name": "Ojokoro Microfinance Bank", "nibbs_code": "090527", "cbn_code": ""},
    {"bank_name": "Mgbidi Microfinance Bank", "nibbs_code": "090528", "cbn_code": ""},
    {"bank_name": "Ampersand Microfinance Bank", "nibbs_code": "090529", "cbn_code": ""},
    {"bank_name": "Confidence MFB", "nibbs_code": "090530", "cbn_code": ""},
    {"bank_name": "Aku Microfinance Bank", "nibbs_code": "090531", "cbn_code": ""},
    {"bank_name": "Polybadan Microfinance Bank", "nibbs_code": "090534", "cbn_code": ""},
    {"bank_name": "Ikoyi-Osun Microfinance Bank", "nibbs_code": "090536", "cbn_code": ""},
    {"bank_name": "Lobrem Microfinance Bank", "nibbs_code": "090537", "cbn_code": ""},
    {"bank_name": "BluePrint Investments Microfinance Bank", "nibbs_code": "090538", "cbn_code": ""},
    {"bank_name": "Enrich Microfinance Bank", "nibbs_code": "090539", "cbn_code": ""},
    {"bank_name": "Aztec Microfinance Bank", "nibbs_code": "090540", "cbn_code": ""},
    {"bank_name": "Excellent Microfinance Bank", "nibbs_code": "090541", "cbn_code": ""},
    {"bank_name": "Otuo Microfinance Bank", "nibbs_code": "090542", "cbn_code": ""},
    {"bank_name": "Iwoama Microfinance Bank", "nibbs_code": "090543", "cbn_code": ""},
    {"bank_name": "Aspire Microfinance Bank", "nibbs_code": "090544", "cbn_code": ""},
    {"bank_name": "Abulesoro Microfinance Bank", "nibbs_code": "090545", "cbn_code": ""},
    {"bank_name": "Ijebu-Ife Microfinance Bank", "nibbs_code": "090546", "cbn_code": ""},
    {"bank_name": "Rockshield Microfinance Bank", "nibbs_code": "090547", "cbn_code": ""},
    {"bank_name": "Ally Microfinance Bank", "nibbs_code": "090548", "cbn_code": ""},
    {"bank_name": "KC Microfinance Bank", "nibbs_code": "090549", "cbn_code": ""},
    {"bank_name": "Green Energy Microfinance Bank", "nibbs_code": "090550", "cbn_code": ""},
    {"bank_name": "FairMoney Microfinance Bank", "nibbs_code": "090551", "cbn_code": ""},
    {"bank_name": "Consistent Trust Microfinance Bank", "nibbs_code": "090553", "cbn_code": ""},
    {"bank_name": "Kayvee Microfinance Bank", "nibbs_code": "090554", "cbn_code": ""},
    {"bank_name": "BishopGate Microfinance Bank", "nibbs_code": "090555", "cbn_code": ""},
    {"bank_name": "Egwafin Microfinance Bank", "nibbs_code": "090556", "cbn_code": ""},
    {"bank_name": "Lifegate Microfinance Bank", "nibbs_code": "090557", "cbn_code": ""},
    {"bank_name": "Shongom Microfinance Bank", "nibbs_code": "090558", "cbn_code": ""},
    {"bank_name": "Shield Microfinance Bank", "nibbs_code": "090559", "cbn_code": ""},
    {"bank_name": "Tanadi Microfinance Bank", "nibbs_code": "090560", "cbn_code": ""},
    {"bank_name": "Akuchuckwu Microfinance Bank", "nibbs_code": "090561", "cbn_code": ""},
    {"bank_name": "Cedar Microfinance Bank", "nibbs_code": "090562", "cbn_code": ""},
    {"bank_name": "Balera Microfinance Bank", "nibbs_code": "090563", "cbn_code": ""},
    {"bank_name": "Supreme Microfinance Bank", "nibbs_code": "090564", "cbn_code": ""},
    {"bank_name": "Oke-Aro Oredegbe Microfinance Bank", "nibbs_code": "090565", "cbn_code": ""},
    {"bank_name": "Okuku Microfinance Bank", "nibbs_code": "090566", "cbn_code": ""},
    {"bank_name": "Orokam Microfinance Bank", "nibbs_code": "090567", "cbn_code": ""},
    {"bank_name": "Broadview Microfinance Bank", "nibbs_code": "090568", "cbn_code": ""},
    {"bank_name": "Qube Microfinance Bank", "nibbs_code": "090569", "cbn_code": ""},
    {"bank_name": "Iyamoye Microfinance Bank", "nibbs_code": "090570", "cbn_code": ""},
    {"bank_name": "Ilaro Poly Microfinance Bank", "nibbs_code": "090571", "cbn_code": ""},
    {"bank_name": "EWT Microfinance Bank", "nibbs_code": "090572", "cbn_code": ""},
    {"bank_name": "Snow MFB", "nibbs_code": "090573", "cbn_code": ""},
    {"bank_name": "First Midas Microfinance Bank", "nibbs_code": "090575", "cbn_code": ""},
    {"bank_name": "Octopus Microfinance Bank", "nibbs_code": "090576", "cbn_code": ""},
    {"bank_name": "Gbede Microfinance Bank", "nibbs_code": "090579", "cbn_code": ""},
    {"bank_name": "Otech Microfinance Bank", "nibbs_code": "090580", "cbn_code": ""},
    {"bank_name": "Stateside Microfinance Bank", "nibbs_code": "090583", "cbn_code": ""},
    {"bank_name": "GOLDMAN MFB", "nibbs_code": "090574", "cbn_code": ""},
    {"bank_name": "Nkpolu-Ust MFB", "nibbs_code": "090535", "cbn_code": ""},
    {"bank_name": "Iwade MFB Ltd", "nibbs_code": "090578", "cbn_code": ""},
    {"bank_name": "Microbiz MFB", "nibbs_code": "090587", "cbn_code": ""},
    {"bank_name": "Orisun MFB", "nibbs_code": "090588", "cbn_code": ""},
    {"bank_name": "Mercury MFB", "nibbs_code": "090589", "cbn_code": ""},
    {"bank_name": "Gabsyn Microfinance Bank Limited", "nibbs_code": "090591", "cbn_code": ""},
    {"bank_name": "Tasued Microfinance Bank", "nibbs_code": "090593", "cbn_code": ""},
    {"bank_name": "Kenechukwu Microfinance Bank", "nibbs_code": "090602", "cbn_code": ""},
    {"bank_name": "Waya Microfinance Bank", "nibbs_code": "090950", "cbn_code": ""},
    {"bank_name": "IBA Microfinance Bank", "nibbs_code": "090598", "cbn_code": ""},
    {"bank_name": "Island Microfinance Bank", "nibbs_code": "090584", "cbn_code": ""},
    {"bank_name": "Ave Maria Microfinance Bank", "nibbs_code": "090600", "cbn_code": ""},
    {"bank_name": "Akpo Microfinance Bank", "nibbs_code": "090608", "cbn_code": ""},
    {"bank_name": "Ummah Microfinance Bank", "nibbs_code": "090609", "cbn_code": ""},
    {"bank_name": "Amoye Microfinance Bank", "nibbs_code": "090610", "cbn_code": ""},
    {"bank_name": "Medef Microfinance Bank", "nibbs_code": "090612", "cbn_code": ""},
    {"bank_name": "IBOLO Microfinance Bank", "nibbs_code": "090532", "cbn_code": ""},
    {"bank_name": "Banc Corp MFB", "nibbs_code": "090581", "cbn_code": ""},
    {"bank_name": "Flourish MFB", "nibbs_code": "090614", "cbn_code": ""},
    {"bank_name": "Beststar MFB", "nibbs_code": "090615", "cbn_code": ""},
    {"bank_name": "Rayyan MFB", "nibbs_code": "090616", "cbn_code": ""},
    {"bank_name": "Macrod MFB", "nibbs_code": "090603", "cbn_code": ""},
    {"bank_name": "Cashbridge Microfinance Bank", "nibbs_code": "090634", "cbn_code": ""},
    {"bank_name": "Iyin Ekiti MFB", "nibbs_code": "090620", "cbn_code": ""},
    {"bank_name": "Creditville MFB", "nibbs_code": "090611", "cbn_code": ""},
    {"bank_name": "MAB Allianz MFB", "nibbs_code": "090623", "cbn_code": ""},
    {"bank_name": "FET", "nibbs_code": "100001", "cbn_code": ""},
    {"bank_name": "Paga", "nibbs_code": "100002", "cbn_code": ""},
    {"bank_name": "Parkway-ReadyCash", "nibbs_code": "100003", "cbn_code": ""},
    {"bank_name": "Opay Digital Services LTD", "nibbs_code": "100004", "cbn_code": ""},
    {"bank_name": "Cellulant", "nibbs_code": "100005", "cbn_code": ""},
    {"bank_name": "eTranzact", "nibbs_code": "100006", "cbn_code": ""},
    {"bank_name": "Stanbic IBTC @ease wallet", "nibbs_code": "100007", "cbn_code": ""},
    {"bank_name": "Ecobank Xpress Account", "nibbs_code": "100008", "cbn_code": ""},
    {"bank_name": "GTMobile", "nibbs_code": "100009", "cbn_code": ""},
    {"bank_name": "TeasyMobile", "nibbs_code": "100010", "cbn_code": ""},
    {"bank_name": "Mkudi", "nibbs_code": "100011", "cbn_code": ""},
    {"bank_name": "VTNetworks", "nibbs_code": "100012", "cbn_code": ""},
    {"bank_name": "AccessMobile", "nibbs_code": "100013", "cbn_code": ""},
    {"bank_name": "FBNMobile", "nibbs_code": "100014", "cbn_code": ""},
    {"bank_name": "Kegow (Chamsmobile)", "nibbs_code": "100036", "cbn_code": ""},
    {"bank_name": "FortisMobile", "nibbs_code": "100016", "cbn_code": ""},
    {"bank_name": "Hedonmark", "nibbs_code": "100017", "cbn_code": ""},
    {"bank_name": "ZenithMobile", "nibbs_code": "100018", "cbn_code": ""},
    {"bank_name": "Fidelity Mobile", "nibbs_code": "100019", "cbn_code": ""},
    {"bank_name": "MoneyBox", "nibbs_code": "100020", "cbn_code": ""},
    {"bank_name": "Eartholeum", "nibbs_code": "100021", "cbn_code": ""},
    {"bank_name": "GoMoney", "nibbs_code": "100022", "cbn_code": ""},
    {"bank_name": "TagPay", "nibbs_code": "100023", "cbn_code": ""},
    {"bank_name": "Zinternet Nigera Limited", "nibbs_code": "100025", "cbn_code": ""},
    {"bank_name": "One Finance", "nibbs_code": "100026", "cbn_code": ""},
    {"bank_name": "Innovectives Kesh", "nibbs_code": "100029", "cbn_code": ""},
    {"bank_name": "EcoMobile", "nibbs_code": "100030", "cbn_code": ""},
    {"bank_name": "FCMB Easy Account", "nibbs_code": "100031", "cbn_code": ""},
    {"bank_name": "Contec Global Infotech Limited (NowNow)", "nibbs_code": "100032", "cbn_code": ""},
    {"bank_name": "PalmPay Limited", "nibbs_code": "100033", "cbn_code": ""},
    {"bank_name": "Zenith Eazy Wallet", "nibbs_code": "100034", "cbn_code": ""},
    {"bank_name": "Access Yello", "nibbs_code": "100052", "cbn_code": ""},
    {"bank_name": "M36", "nibbs_code": "100035", "cbn_code": ""},
    {"bank_name": "TitanPaystack", "nibbs_code": "100039", "cbn_code": ""},
    {"bank_name": "Taj_Pinspay", "nibbs_code": "080002", "cbn_code": ""},
    {"bank_name": "Intellifin", "nibbs_code": "100027", "cbn_code": ""},
    {"bank_name": "PayAttitude Online", "nibbs_code": "110001", "cbn_code": ""},
    {"bank_name": "Flutterwave Technology Solutions Limited", "nibbs_code": "110002", "cbn_code": ""},
    {"bank_name": "Interswitch Limited", "nibbs_code": "110003", "cbn_code": ""},
    {"bank_name": "First Apple Limited", "nibbs_code": "110004", "cbn_code": ""},
    {"bank_name": "3line Card Management Limited", "nibbs_code": "110005", "cbn_code": ""},
    {"bank_name": "Paystack Payment Limited", "nibbs_code": "110006", "cbn_code": ""},
    {"bank_name": "Teamapt Limited", "nibbs_code": "110007", "cbn_code": ""},
    {"bank_name": "Cyberspace Limited", "nibbs_code": "110014", "cbn_code": ""},
    {"bank_name": "Vas2nets Limited", "nibbs_code": "110015", "cbn_code": ""},
    {"bank_name": "Crowdforce", "nibbs_code": "110017", "cbn_code": ""},
    {"bank_name": "Prophius", "nibbs_code": "110032", "cbn_code": ""},
    {"bank_name": "Accelerex Network Limited", "nibbs_code": "090202", "cbn_code": ""},
    {"bank_name": "NIP Virtual Bank", "nibbs_code": "999999", "cbn_code": ""},
    {"bank_name": "9Payment Service Bank", "nibbs_code": "120001", "cbn_code": ""},
    {"bank_name": "HopePSB", "nibbs_code": "120002", "cbn_code": ""},
    {"bank_name": "MoMo PSB", "nibbs_code": "120003", "cbn_code": ""},
    {"bank_name": "SmartCash PSB", "nibbs_code": "120004", "cbn_code": ""}
]

def seed_financial_institutions(db: Session):
    global banks
    provider_id = 0
    provider = get_single_provider_by_code(db=db, code="squadco")
    if provider is not None:
        provider_id = provider.id
    if len(banks) > 0:
        for bank in banks:
            create_financial_institution(db=db, provider_id=provider_id, name=bank['bank_name'], code=bank['cbn_code'], nibss_code=bank['nibbs_code'], status=1)
    return True